config/routes.rb
Rails.application.routes.default_url_options[:host] = "ga-quiz.herokuapp.com"
Rails.application.routes.draw do

  namespace :groups do
    resources :regroups
  end

  namespace :quizzes do
    resources :answers
  end

  resources :quizzes, module: :quizzes, as: 'quizzes_quiz'
  resources :quizzes, module: :quizzes do
    resources :assessments do
      put :finish_all, on: :collection
    end
    resources :questions
  end
  get '/quizzes', to: 'quizzes/quiz#index', as: 'quizzes_quizzes'
  namespace :quizzes do
    resources :answers
    resources :questions
    resources :assessments
  end

  resources :sessions

  resources :users do
    resources :sessions
  end

  resources :groups do
    resources :quizzes, module: :quizzes
    resources :regroups, module: :groups
    resources :users, except: [:new, :create]
    resources :group_members, as: :member
    post :copy, on: :member
  end
  resources :group_members

  root to: 'sessions#new'
  match '*all', :to => 'application#not_found', via: :all, constraints: { all: /(?!rails)/ }
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :quizzes, class_name: 'Quizzes::Quiz', dependent: :destroy
  has_many :group_members, dependent: :destroy
  accepts_nested_attributes_for :group_members, allow_destroy: true
  has_many :users, through: :group_members

  has_many :instructors, -> { where( group_members: { role: 'instructor' } ) }, through: :group_members, source: :user
  has_many :students, -> { where( group_members: { role: 'student' } ) }, through: :group_members, source: :user
  has_many :members, -> { where( group_members: { role: 'member' } ) }, through: :group_members, source: :user

  has_many :regroups, class_name: 'Groups::Regroup', dependent: :destroy

  scope :active, -> { where('(groups.start_at IS NULL OR NOW() > groups.start_at) AND (groups.end_at IS NULL OR NOW() < groups.end_at)') }

  def self.administrators
    Group.find(1)
  end

  def self.instructors
    Group.find(2)
  end

end

app/models/groups.rb
module Groups
  def self.table_name_prefix
    'groups_'
  end
end

app/models/groups/regroup.rb
class Groups::Regroup < ActiveRecord::Base
  belongs_to :group
  has_many :regroup_groups, dependent: :destroy
  accepts_nested_attributes_for :regroup_groups

  def build
    students = group.students.sort_by { |student| (student.answers.average(:grade) || 0) + (rand-0.5)/10 }
    splits = students.in_groups_of(target_group_size, false)
    if leads = splits.shift
      regroups = leads.zip(*splits)
      regroups.each_with_index do |students, index|
        regroup_groups.build(users: students.compact, name: "Group #{index+1}")
      end
    end
  end

end

app/models/groups/regroup_group.rb
class Groups::RegroupGroup < ActiveRecord::Base
  belongs_to :regroup
  has_many :regroup_group_members, dependent: :delete_all
  has_many :users, through: :regroup_group_members
end

app/models/groups/regroup_group_member.rb
class Groups::RegroupGroupMember < ActiveRecord::Base
  belongs_to :regroup_group
  belongs_to :user
end

app/controllers/groups/regroups_controller.rb
class Groups::RegroupsController < ApplicationController
  before_action :set_group
  before_action :set_groups_regroup, only: [:show, :edit, :update, :destroy]

  # GET /groups/regroups
  # GET /groups/regroups.json
  def index
    @groups_regroups = @group.regroups.to_a
    @new_regroup = @group.regroups.new
  end

  # GET /groups/regroups/1
  # GET /groups/regroups/1.json
  def show
    @new_regroup = @group.regroups.new(@groups_regroup.attributes)
    respond_to do |format|
      format.any(:html, :json)
      format.md do
        response.headers['Content-Disposition'] = 'attachment; filename="' + @groups_regroup.name.parameterize + '.md"'
        render
      end
    end
  end

  # GET /groups/regroups/new
  def new
    if params[:groups_regroup]
      case params[:preset]
      when 'pair'
        @groups_regroup = @group.regroups.new(target_group_size: @group.students.count / 2)
        @groups_regroup.build
      when 'standup'
        @groups_regroup = @group.regroups.new(target_group_size: @group.instructors.count + @group.members.count)
        @groups_regroup.build
        @groups_regroup.regroup_groups.zip(@group.instructors + @group.members).each do |regroup, instructor|
          regroup.name = "#{instructor.name.split.first}'s Group"
        end
      when 'instructor'
        @groups_regroup = @group.regroups.new(target_group_size: @group.instructors.count)
        @groups_regroup.build
        @groups_regroup.regroup_groups.zip(@group.instructors).each do |regroup, instructor|
          regroup.name = "#{instructor.name.split.first}'s Group"
        end
      else
        @groups_regroup = @group.regroups.new(groups_regroup_params)
        @groups_regroup.build
      end
    else
      @groups_regroup = @group.regroups.new
    end
    @new_regroup = @groups_regroup
  end

  # GET /groups/regroups/1/edit
  def edit
    @new_regroup = Groups::Regroup.new(@groups_regroup.attributes)
  end

  # POST /groups/regroups
  # POST /groups/regroups.json
  def create
    @groups_regroup = Groups::Regroup.new(groups_regroup_params)
    @group = @groups_regroup.group

    respond_to do |format|
      if @groups_regroup.save
        format.html { redirect_to group_regroup_path(@group, @groups_regroup), notice: 'Regroup was successfully created.' }
        format.json { render :show, status: :created, location: @groups_regroup }
      else
        format.html { render :new }
        format.json { render json: @groups_regroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/regroups/1
  # PATCH/PUT /groups/regroups/1.json
  def update
    @group = @groups_regroup.group
    respond_to do |format|
      if @groups_regroup.update(groups_regroup_params)
        format.html { redirect_to group_regroup_path(@group, @groups_regroup), notice: 'Regroup was successfully updated.' }
        format.json { render :show, status: :ok, location: @groups_regroup }
      else
        format.html { render :edit }
        format.json { render json: @groups_regroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/regroups/1
  # DELETE /groups/regroups/1.json
  def destroy
    @groups_regroup.destroy
    respond_to do |format|
      format.html { redirect_to group_regroups_url(@groups_regroup.group), notice: 'Regroup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_group
      @group = Group.find(params[:group_id]) if params[:group_id]
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_groups_regroup
      @groups_regroup = Groups::Regroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def groups_regroup_params
      params.require(:groups_regroup).permit(:group_id, :name, :target_group_size, regroup_groups_attributes: [ :id, :name, user_ids: [] ])
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :copy, :destroy]

  before_action except: :show do
    forbidden unless \
      group_role?(@group, :member, :owner, :instructor) ||
      group_role?(Group.administrators, :member, :owner)
  end

  before_action only: :show do
    forbidden unless \
      group_role?(@group, :member, :owner, :instructor, :student) ||
      group_role?(Group.administrators, :member, :owner)
  end

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        @group.group_members.create!(user: current_user, role: 'owner')
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /groups/1/copy
  # GET /groups/1/copy.json
  def copy
    @group_copy = @group.deep_clone include: { quizzes: { questions: :options } }
    respond_to do |format|
      if @group_copy.save
        @group_copy.group_members.create!(user: current_user, role: 'owner')
        format.html { redirect_to edit_group_url(@group_copy), notice: 'Group was successfully copied.'}
        format.json { render :show, status: :created, location: @group_copy }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :start_at, :end_at, group_members_attributes: [:id, :role, :_destroy])
    end
end

app/helpers/groups/regroups_helper.rb
module Groups::RegroupsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/regroups/_form.html.slim
- if @groups_regroup.errors.any?
  #error_explanation
    h2 = "#{pluralize(@groups_regroup.errors.count, "error")} prohibited this groups_regroup from being saved:"
    ul
      - @groups_regroup.errors.full_messages.each do |message|
        li = message

= form.hidden_field :group_id
= form.hidden_field :target_group_size

.field
  - form.object.regroup_groups.in_groups_of(4, false).each do |group_row|
    .row
      - group_row.each do |group|
        = form.fields_for :regroup_groups, group do |group_form|
          .small-3.columns.end
            = group_form.text_field :name
            ul.no-bullet
              - group.users.each do |user|
                = group_form.hidden_field :user_ids, value: user.id, multiple: true
                li = render user
hr
.field.row
  .small-2.columns
    = form.label :name
  .small-9.columns.end
    = form.text_field :name

app/views/groups/regroups/edit.html.slim
.row
  h1 Editing #{@groups_regroup.name}

= form_for @groups_regroup do |form|
  == render form
  .actions.text-center.row
    .small-10.columns
      = form.submit 'Save Regrouping', class: 'button primary'
      = link_to 'Cancel', @groups_regroup
    .small-2.columns = link_to 'Delete', @groups_regroup, method: :DELETE, class: 'button warning'

app/views/groups/regroups/index.html.slim
- if @groups_regroups.any?
  - @groups_regroups.each do |groups_regroup|
    .row
      .small-offset-2.small-4.columns
        p = link_to groups_regroup.name.present? ? groups_regroup.name : "No Name", group_regroup_path(@group, groups_regroup)
      .small-2.columns
        = groups_regroup.created_at.to_date.to_s(:long)
      .small-3.columns.end
        | #{groups_regroup.target_group_size} groups

app/views/groups/regroups/new.html.slim
= form_for @groups_regroup do |form|
  == render form
  .actions.text-center
    = form.submit 'Save Regrouping', class: 'button primary'

app/views/groups/regroups/show.html.slim
.row
  .right
    = link_to 'Edit', edit_group_regroup_path(@group, @groups_regroup), class: 'button tiny secondary'
    = link_to 'Download', group_regroup_path(@group, @groups_regroup, :md), class: 'button tiny'
  h1
    = @group.name
    | &nbsp;&mdash;&nbsp;
    = @groups_regroup.name

- @groups_regroup.regroup_groups.in_groups_of(4, false).each do |group_row|
  .row
    - group_row.each do |group|
      .small-3.columns.end
        br
        h3 = group.name
        ul.no-bullet
          - group.users.each do |user|
            li = render user

app/views/groups/regroups/show.md.erb
<% rows = @groups_regroup.regroup_groups.map{ |regroup| regroup.users.count }.max %>
# <%= @groups_regroup.name %>
### <%= @group.name %>

|<% @groups_regroup.regroup_groups.each do |group| %> <%= group.name.ljust(24) %>|<% end %>
|<% @groups_regroup.regroup_groups.each do |group| %><%= "-"*25 %>|<% end %>
<% rows.times do |row| %>
|<% @groups_regroup.regroup_groups.each do |group| %> <%= (group.users[row].try(:name)||"").ljust(24) %>|<% end %>
<% end %>

---

<% @groups_regroup.regroup_groups.each do |group| %>
#### <%= group.name %>

<% group.users.each do |user| %>
- <%= user.name %>
<% end %>

<% end %>