config/routes.rb
Rails.application.routes.default_url_options[:host] = "ga-quiz.herokuapp.com"
Rails.application.routes.draw do

  namespace :groups do
    resources :regroups
  end

  namespace :quizzes do
    resources :answers
  end

  resources :quizzes, module: :quizzes, as: 'quizzes_quiz'
  resources :quizzes, module: :quizzes do
    resources :assessments do
      put :finish_all, on: :collection
    end
    resources :questions
  end
  get '/quizzes', to: 'quizzes/quiz#index', as: 'quizzes_quizzes'
  namespace :quizzes do
    resources :answers
    resources :questions
    resources :assessments
  end

  resources :sessions

  resources :users do
    resources :sessions
  end

  resources :groups do
    resources :quizzes, module: :quizzes
    resources :regroups, module: :groups
    resources :users, except: [:new, :create]
    resources :group_members, as: :member
    post :copy, on: :member
  end
  resources :group_members

  root to: 'sessions#new'
  match '*all', :to => 'application#not_found', via: :all, constraints: { all: /(?!rails)/ }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :memberships, class_name: 'GroupMember', dependent: :destroy
  has_many :groups, -> { order(:start_at) }, through: :memberships
  has_many :sessions, dependent: :destroy
  has_many :answers, class_name: 'Quizzes::Answer'
  has_many :assessments, class_name: 'Quizzes::Assessment'

  has_many :quizzes, through: :groups

  validates :name, presence: true
  validates :email, presence: true, email: true

  def incomplete_quizzes
    quizzes.joins("LEFT OUTER JOIN quizzes_assessments ON quizzes_assessments.quiz_id = quizzes_quizzes.id AND quizzes_assessments.user_id = '#{id}'").where('quizzes_assessments.finished_at IS NULL')
  end

  def to_s
    name
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  private

  # Use callbacks to share common setup or constraints between actions.
  before_action :set_group
  def set_group
    @group = Group.find(params[:group_id]) if params[:group_id]
  end

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def set_user
    if @group
      @user = @group.users.find(params[:id])
      @group_member = @group.group_members.where(user: @user).first
    else
      @user = User.find(params[:id])
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  public

  # GET /users
  # GET /users.json
  def index
    return forbidden unless group_role?(@group, :instructor, :owner, :member) || group_role?(Group.administrators, :member, :owner)
    @users = User.all
    render layout: 'application'
  end

  # GET /users/1
  # GET /users/1.json
  def show
    if @group
      return forbidden unless current_user == @user || group_role?(@group, :instructor, :owner, :member) || group_role?(Group.administrators, :member, :owner)
      @assessment = @user.answers.joins(:question).select('quizzes_questions.topic, quizzes_answers.grade').group('quizzes_questions.topic')
      @performance = Hash[@assessment.average('quizzes_answers.grade').sort_by{|k,v|v.to_f}]
      @completed_assessments = @user.assessments.finished
      render "show-#{@group_member.role}"
    else
      return forbidden unless current_user == @user || group_role?(Group.administrators, :member, :owner)
    end
  end

  # GET /users/1/edit
  def edit
    return forbidden unless current_user == @user || group_role?(Group.administrators, :member, :owner)
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    return forbidden unless current_user == @user || group_role?(Group.administrators, :member, :owner)
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    return forbidden unless current_user == @user || group_role?(Group.administrators, :member, :owner)
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.slim
= content_tag_for :div, user do
  = image_tag gravatar_url(user.email, size: 48), width: 48, height: 48, draggable: false
  span.name = user.name

app/views/users/edit.html.slim
h1 Settings

= form_for @user do |form|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field.row
    .small-3.columns
      = form.label :name
    .small-8.columns
      = form.text_field :name
    .small-1.column &nbsp;
  .field.row
    .small-3.columns
      = form.label :email
    .small-8.columns
      = form.email_field :email
    .small-1.column &nbsp;
  .field.row
    .small-3.columns
      = form.label :password
    .small-8.columns
      = form.password_field :password
    .small-1.column &nbsp;
  .field.row
    .small-3.columns
      = form.label :password_confirmation, 'Retype Password'
    .small-8.columns
      = form.password_field :password_confirmation
    .small-1.column &nbsp;
  .actions.row
    .small-3.columns &nbsp;
    .small-8.columns
      = form.submit 'Save Changes', class: 'button primary'
      | &nbsp;&nbsp;&nbsp;
      = link_to 'Cancel', @user
    .small-1.columns &nbsp;

app/views/users/index.html.slim
.row
  h1 All Users

.row
  table
    thead
      tr
        th Name
        th Email
        th Group
        th
        th

    tbody
      - @users.each do |user|
        tr
          td = link_to user.name, user
          td = user.email
          td
            = user.groups.last.try(:name) || content_tag(:i, 'None')
            - count = user.groups.count - 1
            = ", and #{count} more" if count > 0
          td = link_to 'Settings', edit_user_path(user)
          td = link_to 'Destroy', user, data: {:confirm => 'Are you sure?'}, :method => :delete

  br

  = link_to 'New User', new_user_path

app/views/users/show-instructor.html.slim
h1
  = @group.name
  small &nbsp;&nbsp;&nbsp;Instructor

app/views/users/show-owner.html.slim
h1
  = @group.name
  small &nbsp;&nbsp;&nbsp;Owner

app/views/users/show-student.html.slim
- content_for :instructions do
  li data-id="user_topical-chart" data-button="Next" data-prev-text="Back" data-options="tip_location: 'left'"
    h4 Topical Chart
    p This chart displays the assessment results by topic and ordered from weakest to highest.
  li data-id="user_completed-assessments" data-button="Next" data-prev-text="Back" data-options="tip_location: 'left'"
    h4 Completed Assessments
    p For all of the completed an assessments, you can see the graded scores here.

- content_for :user_navigation do
  li = link_to "Topical Chart", "#user_topical-chart"
  li = link_to "Completed Assessments", "#user_completed-assessments"
  - if group_role?(Group.administrators, :member, :owner)
    li = link_to "Reset Password", edit_user_path(@user)

- if @performance
  div#user_topical-chart
    ruby:
      data = {
        labels: @performance.keys,
        datasets: [
          {
            label: "Performance",
            fillColor: "rgba(151,187,205,0.2)",
            strokeColor: "rgba(151,187,205,1)",
            pointColor: "rgba(151,187,205,1)",
            pointStrokeColor: "#fff",
            pointHighlightFill: "#fff",
            pointHighlightStroke: "rgba(151,187,205,1)",
            data: @performance.values.map(&:to_f),
          }
        ]
      }
    h3 Topical Chart
    = radar_chart data, { height: 436, width: 600, animation: false, scaleOverride: true, scaleStartValue: 0, scaleStepWidth: 0.25, scaleSteps: 4, generateLegend: true }
    div#topical_spider_graph_legend
  br

- if @completed_assessments
  div#user_completed-assessments
    h3 Completed Assessments
    table.assessments width="100%"
      thead
        tr
          th Quiz
          th width=1 Score
      - @completed_assessments.each do |assessment|
        tr
          td.name = link_to assessment.quiz.to_s, assessment
          - if average_grade = assessment.answers.average(:grade)
            td.average = number_to_percentage average_grade * 100, precision: 0

- 12.times do
  br

app/views/users/show.html.slim
ul.memberships
  - @user.memberships.each do |membership|
    li
      = link_to membership.group.name, group_user_path(membership.group, membership.user)
      small
        | &nbsp;&mdash;&nbsp;
        = t membership.role