config/routes.rb
Rails.application.routes.default_url_options[:host] = "ga-quiz.herokuapp.com"
Rails.application.routes.draw do

  namespace :groups do
    resources :regroups
  end

  namespace :quizzes do
    resources :answers
  end

  resources :quizzes, module: :quizzes, as: 'quizzes_quiz'
  resources :quizzes, module: :quizzes do
    resources :assessments do
      put :finish_all, on: :collection
    end
    resources :questions
  end
  get '/quizzes', to: 'quizzes/quiz#index', as: 'quizzes_quizzes'
  namespace :quizzes do
    resources :answers
    resources :questions
    resources :assessments
  end

  resources :sessions

  resources :users do
    resources :sessions
  end

  resources :groups do
    resources :quizzes, module: :quizzes
    resources :regroups, module: :groups
    resources :users, except: [:new, :create]
    resources :group_members, as: :member
    post :copy, on: :member
  end
  resources :group_members

  root to: 'sessions#new'
  match '*all', :to => 'application#not_found', via: :all, constraints: { all: /(?!rails)/ }
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "General Assembly - Quizzes" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= stylesheet_link_tag    "http://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.min.css" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-60990509-1', 'auto');
      $(document).on('page:change', function() { ga('send', 'pageview'); })
      ga('send', 'pageview');
    </script>
  </head>

  <body>

    <% cache [current_session, :nav, @group] do %>
      <nav class="top-bar" data-topbar role="navigation">
        <ul class="title-area">
          <li class="name">
            <h1><%= link_to image_tag('ga-lockup.png', alt: 'General Assembly', style: 'max-height: 60%'), root_path %></h1>
          </li>
          <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
          <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>

        <section class="top-bar-section">
          <!-- Right Nav Section -->
          <ul class="right" id="auth-section" class="expose-instructions">
            <% if logged_in? %>
              <% active_group = (@group && @group.persisted? ? @group : current_user.groups.last) %>
              <% if current_user.groups.count > 1 %>
                <li class="active has-dropdown">
                  <%= link_to active_group.name, active_group %>
                  <ul class="dropdown">
                    <% current_user.groups.reject { |group| group == active_group }.each do |group| %>
                      <li><%= link_to group.name, group %></li>
                    <% end %>
                  </ul>
                </li>
              <% else %>
                <li class="active"><%= link_to current_user.groups.first.name, group_quizzes_path(current_user.groups.first) %></li>
              <% end %>
              <li class="has-dropdown">
                <%= link_to current_user.name, user_session_path(current_user, current_session) %>
                <ul class="dropdown">
                  <li><%= link_to 'Profile', group_user_path(active_group, current_user) %></li>
                  <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
                  <li><%= link_to 'Log Out', session_path(current_session), method: 'delete' %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log In", new_session_path %></li>
            <% end %>
          </ul>

          <% if logged_in? %>
            <!-- Left Nav Section -->
            <ul class="left">
              <li><a href="#" id="start-instructions">Instructions</a></li>
            </ul>
          <% end %>
        </section>
      </nav>
    <% end %>

    <div class="row" style="margin-top: 1em">
      <% if display_notice = notice %>
        <div class="alert-box small-12 columns" data-alert>
          <%= display_notice %>
          <div class="close">&times;</div>
        </div>
      <% end %>
    </div>

    <%= content_for(:sublayout) ? yield(:sublayout) : yield %>

    <ol class="joyride-list" data-joyride>
      <li data-id="" data-button="Start" data-options="prev_button: false">
        <h4>Instructions</h4>
        <br />
        <p>This guide has been created to assist you with the features of this application.</p>
      </li>
      <li data-id="auth-section" data-text="Next" data-options="tip_location: bottom; prev_button: false">
        <p>This menu allows you to view your profile, your groups, and change your settings.</p>
      </li>
      <%= yield :instructions %>
      <li data-id="" data-button="Thank You!" data-options="prev_button: false">
        <h4>Instructions</h4>
        <br />
        <p>That's all for now.  Thank you for using GA-QUIZ!</p>
      </li>
    </ol>

  </body>
</html>

app/views/layouts/users.html.slim
- content_for :instructions do
  li data-id="user_info" data-text="Next" data-prev-text="Back"
    h4 User Info
    p Here is the profile information for this user, including all their associations.

- content_for :sublayout do
  .row
    .medium-4.columns#user_info
      .gravatar = image_tag gravatar_url(@user.email, size: 256, default: 'retro')
      br
      h1 = @user.name
      p.lead = @user.email

      - if content_for?(:user_navigation)
        ul#user_navigation.no-bullet
          = yield :user_navigation

    .medium-8.columns
      = yield

= render template: 'layouts/application'